### PR TITLE
Fixes #114 - animates closing of trail details

### LINKED ISSUE #114: Animate close of trail details when close-btn tapped
#### Description

When a trailhead is tapped, the trail-details gracefully animate into view from the bottom of the screen. When the close-btn is tapped, the trail-details simply flash close.
#### Actions

When the close button (the white x) is tapped, or when the trail-view is closed because the user taps on the map, let's animate the trail-view back down, paralleling the movement when opened.

### PR DESCRIPTION
**Pull request by anselmbradford**
- Changes how trail details animates by utilizing the `top` property
  and `calc()` notation to reduce the number of variables in the
  setTrailViewOffset() method.
- Performs CSS cleanup around trail details elements by removing unnecessary properties.
- Performs HTML cleanup by removing unneeded nesting and assigning IDs
  to elements that are retrieved by JS.
- Migrates some HTML elements around the trail details to semantic
  elements so the nesting of elements is easier to see in the source HTML.
- Adds methods to controller for toggling trail details, and
  consolidates code around toggling the trail details. Also, creates
  variables for DOM elements that were looked up repeatedly.

Of note, the trail details page is no longer hidden with ng-show; it’s
simply moved out of view. This is to accommodate animating it out of
view when the view changes to the map view. It’s at a 3000 z-index, so
anything that should appear on top of it should be greater than
z-index:3000.

### CODE REVIEW

**Comment by anselmbradford** [comment]
@alanjosephwilliams I noticed some performance lags in the emulator. You'll have to check on a device how it is. Works great in the web served version, but in the emulator it's a bit sluggish. In the following animation you'll see two clicks are necessary to click a marker after the trail details are closed (this is the case on master too in the emulator, so its not just this branch). Also, the closing of the trail details isn't super smooth in the emulator (in fact it doesn't look to be animating at all in the gif, but that's just because of the low framerate in the gif). Hopefully it's better on a device.

 animated-trail-details

(Also, FYI, the marker that's clicked at the end that doesn't do anything is one of these trailheads --> https://github.com/codeforamerica/trails-mobile/issues/84)

**Comment by anselmbradford** [comment]
@alanjosephwilliams I'll update this to resolve conflicts.

**Comment by alanjosephwilliams** [comment]
Also Ans--not sure if it was intended, but the left and right margins
"above the fold" on the trail-view have doubled. We should bring them back
in line with other margins.

On Mon, May 12, 2014 at 9:31 AM, Ans notifications@github.com wrote:

> @alanjosephwilliams https://github.com/alanjosephwilliams I'll update
> this to resolve conflicts.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/codeforamerica/trails-mobile/pull/126#issuecomment-42854943
> .

## 

t:  @alanjosephwilli
p: 817 713 6264

**Comment by anselmbradford** [comment]
@alanjosephwilliams All better!

Screenshots show differing title lengths:
screen shot 2014-05-12 at 10 32 28 am

screen shot 2014-05-12 at 10 32 46 am

screen shot 2014-05-12 at 10 32 58 am

**Comment by alanjosephwilliams** [comment]
@anselmbradford --I think the best use of your time tomorrow or Sunday would be an investigation of the performance lags you noted. Also see #129--that was not a problem we had reported previously. My hope (for an easy diagnosis' sake) is that the some of the changes logged here may have contributed. In particular, I would explore rolling back the changes to _how_ the animations are performed. 

In fact, I think that I remember Rob Brackett (who I am subtweeting / subgithubbing because he is in Asia and shouldn't be bothered) mentioning that the "top" property should be avoided...

If the downside to using the previous method was simply idiomatic, then let's consider reverting. If we don't see performance improvements, let's discuss how else we might be able to diagnose the problem.

**Pull request merged**
