### PR TITLE
Geolocation waits for device to be ready

### PR DESCRIPTION
**Pull request by anselmbradford**
Adds event listener to wait for the device to be ready before watching
for position.

### CODE REVIEW

**Comment by anselmbradford** [comment]
@alanjosephwilliams Try pulling this branch and checking on device. I can't see the message without being on a device, but this post says to wait for the device to be ready before requesting the position: http://stackoverflow.com/questions/1673579/location-permission-alert-on-iphone-with-phonegap

**Comment by anselmbradford** [comment]
Referencing https://github.com/codeforamerica/trails-mobile/issues/140

**Comment by lovehandle** [comment]
The angular code (which contains the geolocation code) isn't being loaded before the deviceready event is fired (to my knowledge).

https://github.com/codeforamerica/trails-mobile/blob/master/www/js/application.js#L11

**Comment by anselmbradford** [comment]
@rclosner Ahh, yeah looks like this PR will be redundant to that. Huh, wonder what else this needs. http://stackoverflow.com/questions/22650015/is-it-possible-to-change-the-default-geolocation-alert-message-in-phonegap-ios suggests it's not possible to change (perhaps without diving into Xcode).

@alanjosephwilliams I can't proceed on this without dev access on a device.

**Comment by jmoe** [comment]
Hey @anselmbradford I did a little poking around with this today. No luck. I actually was chatting with a phonegap dev on twitter. He was stumped. Will get back to it.

**Pull request closed without merging**
